### PR TITLE
fix file size check

### PR DESCRIPTION
**Pull request by akki91**
- Current condition matches if request size is exactly 10Mb
- Fixed the condition to check if request size is greater than equal to 10Mb

### CODE REVIEW

**Comment by bbondy** [comment]
The fix seems correct but I'm concerned we have some components >= 10MiB and it could cause an issue.  We need to ensure that the correct code doesn't cause an issue in production first by checking if the existing components are always < 10MiB and won't grow past that threshold.  Basically right now we simply don't have a check enforced because the condition is never hit. 
An alternate path would be to just remove the condition entirely.

**Comment by akki91** [comment]
> I'm concerned we have some components >= 10MiB

@bbondy Does the request size reach greater than equal to 10MiB? If this is the case, the alternate path of removing the check is the best way to move forward.

**Comment by bbondy** [comment]
oh I see, I think this is just the response XML and not the actual component right?

**Comment by akki91** [comment]
> not the actual component right?

Yes that is correct, it is only checking the size of `request`

**Review by bbondy — CHANGES_REQUESTED** [review]
Nevermind, someone internally noticed that body, err := ioutil.ReadAll(io.LimitReader(r.Body, limit)) will read at most `limit` so the check is actually correct as is.

**Pull request closed without merging**
