### PR TITLE
forward logs to aws cloudwatch

### PR DESCRIPTION
**Pull request by linhkikuchi**
Closes https://github.com/brave/go-update/issues/39

### CODE REVIEW

**Comment by mihaiplesa** [comment]
Travis CI check seems stuck, might have to push something to restart.

**Comment by mihaiplesa** [comment]
Any ideas @jumde?

```
controller/controller.go:163:18: S1039: unnecessary use of fmt.Sprintf (gosimple)
			http.Error(w, fmt.Sprintf("No extension ID specified."), http.StatusBadRequest)
			              ^
Makefile:12: recipe for target 'lint' failed
```

**Comment by jumde** [comment]
@mihaiplesa - This happens when the request for the go-updater does not contain a valid `component id`. Can you share the request that triggered this error?

**Comment by mihaiplesa** [comment]
@jumde that's from Travis CI on this PR

**Comment by jumde** [comment]
> @jumde that's from Travis CI on this PR

@mihaiplesa - I was able to reproduce this, `golangci-lint` is causing the issue. Let me create a PR for go-update.

**Comment by mihaiplesa** [comment]
@jumde you can add to this PR if you prefer. Also seeing https://github.com/brave/go-update/issues/35

**Pull request merged**
