### PR TITLE
Add support for tor linux-arm64

### PR DESCRIPTION
**Pull request by linhkikuchi**
For https://github.com/brave/devops/issues/8519
For https://github.com/brave/brave-core-crx-packager/issues/569

### CODE REVIEW

**Review by mihaiplesa — DISMISSED** [review]

**Review by fmarier — COMMENTED** [review]
I think @boocmp was hoping to put the two architectures inside the same extension/component, but I'm not sure.

**Review by mihaiplesa — APPROVED** [review]

**Comment by prusnak** [comment]
When will the CRX file appear at https://tor.bravesoftware.com/release/monolafkoghdlanndjfeebmdfkbklejg ?

**Comment by linhkikuchi** [comment]
> When will the CRX file appear at https://tor.bravesoftware.com/release/monolafkoghdlanndjfeebmdfkbklejg ?

@prusnak it's already there: https://tor.bravesoftware.com/release/monolafkoghdlanndjfeebmdfkbklejg/extension_1_0_3.crx

**Comment by prusnak** [comment]
> > When will the CRX file appear at https://tor.bravesoftware.com/release/monolafkoghdlanndjfeebmdfkbklejg ?
> 
> @prusnak it's already there: https://tor.bravesoftware.com/release/monolafkoghdlanndjfeebmdfkbklejg/extension_1_0_0.crx

Ah, I thought it has the same version as the others (1_0_30). Thanks

**Pull request merged**
